server:
  port: 8090

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client
          uri: http://localhost:8081
          predicates:
            - Path=/api/client/**
        - id: concert
          uri: http://localhost:8082
          predicates:
            - Path=/api/concert/**